wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: xgboost
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1688066057
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.11
      6: 4.17.0
      8:
      - 5
config:
  desc: null
  value: conf/linear_classification.yaml
inherit:
  desc: null
  value:
  - /data/jiachen/in-context-learning/src_bai/conf/linear_regression.yaml
model:
  desc: null
  value:
    encoder_activation: relu
    family: EncoderTF
    n_dims: 20
    n_embd: 64
    n_head: 8
    n_layer: 12
    n_positions: 101
    normalize_attn: true
out_dir:
  desc: null
  value: ../encoder_final/linear_classification/3ffd19cf-4d9b-4550-a9bf-8cdfe1db30a4
test_run:
  desc: null
  value: false
training:
  desc: null
  value:
    batch_size: 64
    curriculum:
      dims:
        end: 20
        inc: 1
        interval: 2000
        start: 10
      points:
        end: 41
        inc: 2
        interval: 2000
        start: 11
    data: gaussian
    keep_every_steps: 100000
    lasso_guided_opt: false
    lasso_guided_opt_lam: 1.0
    lasso_guided_opt_layer: -2
    lasso_guided_opt_token: -1
    learning_rate: 0.0001
    learning_rate_override: false
    num_tasks: null
    num_training_examples: null
    optimizer_reset: false
    resume_id: null
    save_every_steps: 1000
    tasks:
    - kwargs: {}
      name: linear_classification
    train_steps: 500001
wandb:
  desc: null
  value:
    entity: nickhclos
    log_every_steps: 100
    name: linear_classification_227
    notes: ''
    project: in-context-training
