config: conf/linear_classification.yaml
inherit:
- /data/jiachen/in-context-learning/src_bai/conf/linear_regression.yaml
model:
  encoder_activation: relu
  family: EncoderTF
  n_dims: 20
  n_embd: 64
  n_head: 8
  n_layer: 12
  n_positions: 101
  normalize_attn: true
out_dir: ../encoder_final/linear_classification/3ffd19cf-4d9b-4550-a9bf-8cdfe1db30a4
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 2000
      start: 10
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  lasso_guided_opt: false
  lasso_guided_opt_lam: 1.0
  lasso_guided_opt_layer: -2
  lasso_guided_opt_token: -1
  learning_rate: 0.0001
  learning_rate_override: false
  num_tasks: null
  num_training_examples: null
  optimizer_reset: false
  resume_id: null
  save_every_steps: 1000
  tasks:
  - kwargs: {}
    name: linear_classification
  train_steps: 500001
wandb:
  entity: nickhclos
  log_every_steps: 100
  name: linear_classification_227
  notes: ''
  project: in-context-training
